#ifndef BLACKBIRD_IOCTL_H
#define BLACKBIRD_IOCTL_H

#include <basetsd.h>

#ifndef CTL_CODE
#include <winioctl.h>
#endif

#define FILE_DEVICE_BLACKBIRD 0x00008337

#define IOCTL_BLACKBIRD_SUBSCRIBE CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_BLACKBIRD_UNSUBSCRIBE CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_BLACKBIRD_GET_EVENT CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x803, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_BLACKBIRD_GET_STATS CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x804, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_BLACKBIRD_SET_PIDS CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_BLACKBIRD_QUERY_PROCESS_IMAGE CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x806, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_BLACKBIRD_SET_SHUTDOWN_MODE CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x807, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_BLACKBIRD_GET_HEALTH CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x808, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_BLACKBIRD_ARM_PENDING_LAUNCH CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x809, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_BLACKBIRD_CONTROL_EXECUTION  CTL_CODE(FILE_DEVICE_BLACKBIRD, 0x80A, METHOD_BUFFERED, FILE_WRITE_DATA)

#define BLACKBIRD_STREAM_HANDLE 0x00000001
#define BLACKBIRD_STREAM_MEMORY 0x00000002
#define BLACKBIRD_STREAM_THREAD 0x00000004
#define BLACKBIRD_STREAM_FILESYSTEM 0x00000008

#define BLACKBIRD_MAX_EVENT_FRAMES 8
#define BLACKBIRD_MAX_FULL_EVENT_FRAMES 32
#define BLACKBIRD_MAX_PID_LIST 64
#define BLACKBIRD_MAX_IMAGE_PATH_CHARS 1024
#define BLACKBIRD_MAX_DEEP_SAMPLE_BYTES 64
#define BLACKBIRD_MAX_STACK_SNAPSHOT_BYTES 256
#define BLACKBIRD_MAX_FILE_PATH_CHARS 520

typedef enum _BLACKBIRD_EVENT_TYPE
{
    BlackbirdEventTypeNone = 0,
    BlackbirdEventTypeHandle = 1,
    BlackbirdEventTypeThread = 2,
    BlackbirdEventTypeFileSystem = 3
} BLACKBIRD_EVENT_TYPE;

typedef enum _BLACKBIRD_FILE_OPERATION
{
    BlackbirdFileOperationUnknown = 0,
    BlackbirdFileOperationCreate = 1,
    BlackbirdFileOperationRead = 2,
    BlackbirdFileOperationWrite = 3,
    BlackbirdFileOperationClose = 4,
    BlackbirdFileOperationCleanup = 5,
    BlackbirdFileOperationSetInformation = 6,
    BlackbirdFileOperationQueryInformation = 7,
    BlackbirdFileOperationDirectoryControl = 8,
    BlackbirdFileOperationFsControl = 9
} BLACKBIRD_FILE_OPERATION;

typedef enum _BLACKBIRD_HANDLE_CLASS
{
    BlackbirdHandleClassUnknown = 0,
    BlackbirdHandleClassLegitimateSyscall = 1,
    BlackbirdHandleClassDirectSyscallSuspect = 2
} BLACKBIRD_HANDLE_CLASS;

typedef struct _BLACKBIRD_SUBSCRIBE_REQUEST
{
    UINT32 ProcessId;
    UINT32 StreamMask;
} BLACKBIRD_SUBSCRIBE_REQUEST, *PBLACKBIRD_SUBSCRIBE_REQUEST;

typedef struct _BLACKBIRD_UNSUBSCRIBE_REQUEST
{
    UINT32 ProcessId;
} BLACKBIRD_UNSUBSCRIBE_REQUEST, *PBLACKBIRD_UNSUBSCRIBE_REQUEST;

typedef struct _BLACKBIRD_GET_EVENT_REQUEST
{
    UINT32 TimeoutMs;
} BLACKBIRD_GET_EVENT_REQUEST, *PBLACKBIRD_GET_EVENT_REQUEST;

typedef struct _BLACKBIRD_SET_PIDS_REQUEST
{
    UINT32 StreamMask;
    UINT32 ProcessCount;
    UINT32 ProcessIds[BLACKBIRD_MAX_PID_LIST];
} BLACKBIRD_SET_PIDS_REQUEST, *PBLACKBIRD_SET_PIDS_REQUEST;

#define BLACKBIRD_PENDING_LAUNCH_FLAG_CLEAR 0x00000001u

typedef struct _BLACKBIRD_ARM_PENDING_LAUNCH_REQUEST
{
    UINT32 StreamMask;
    UINT32 Flags;
    WCHAR ImagePathNormDos[BLACKBIRD_MAX_IMAGE_PATH_CHARS];
    WCHAR ImagePathNormNt[BLACKBIRD_MAX_IMAGE_PATH_CHARS];
    WCHAR ImagePathTail[BLACKBIRD_MAX_IMAGE_PATH_CHARS];
} BLACKBIRD_ARM_PENDING_LAUNCH_REQUEST, *PBLACKBIRD_ARM_PENDING_LAUNCH_REQUEST;

typedef struct _BLACKBIRD_QUERY_PROCESS_IMAGE_REQUEST
{
    UINT32 ProcessId;
} BLACKBIRD_QUERY_PROCESS_IMAGE_REQUEST, *PBLACKBIRD_QUERY_PROCESS_IMAGE_REQUEST;

typedef struct _BLACKBIRD_CONTROL_EXECUTION_REQUEST
{
    UINT32 ProcessId;
    UINT32 Suspend; /* 1 = suspend, 0 = resume */
} BLACKBIRD_CONTROL_EXECUTION_REQUEST, *PBLACKBIRD_CONTROL_EXECUTION_REQUEST;

typedef struct _BLACKBIRD_QUERY_PROCESS_IMAGE_RESPONSE
{
    UINT32 ProcessId;
    INT32 Status;
    WCHAR ImagePath[BLACKBIRD_MAX_IMAGE_PATH_CHARS];
} BLACKBIRD_QUERY_PROCESS_IMAGE_RESPONSE, *PBLACKBIRD_QUERY_PROCESS_IMAGE_RESPONSE;

typedef struct _BLACKBIRD_EVENT_HEADER
{
    UINT32 Size;
    UINT32 Type;
    UINT32 StreamMask;
    UINT32 Sequence;
    INT64 TimestampQpc;
} BLACKBIRD_EVENT_HEADER, *PBLACKBIRD_EVENT_HEADER;

typedef struct _BLACKBIRD_HANDLE_EVENT
{
    UINT64 CallerPid;
    UINT64 TargetPid;
    UINT32 DesiredAccess;
    UINT32 ClassId;
    UINT64 OriginAddress;
    UINT32 OriginProtect;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[BLACKBIRD_MAX_EVENT_FRAMES];
    INT32 StatusOpenProcess;
    INT32 StatusBasicInfo;
    INT32 StatusSectionName;
    UINT64 DeepAllocationBase;
    UINT64 DeepRegionSize;
    UINT32 DeepRegionProtect;
    UINT32 DeepRegionState;
    UINT32 DeepRegionType;
    UINT32 DeepSampleSize;
    UINT8 DeepSample[BLACKBIRD_MAX_DEEP_SAMPLE_BYTES];
    WCHAR OriginPath[260];
    UINT32 CaptureFlags;
    UINT32 FullFrameCount;
    UINT64 FullFrames[BLACKBIRD_MAX_FULL_EVENT_FRAMES];
    UINT64 RegRax;
    UINT64 RegRbx;
    UINT64 RegRcx;
    UINT64 RegRdx;
    UINT64 RegRsi;
    UINT64 RegRdi;
    UINT64 RegRbp;
    UINT64 RegRsp;
    UINT64 RegR8;
    UINT64 RegR9;
    UINT64 RegR10;
    UINT64 RegR11;
    UINT64 RegR12;
    UINT64 RegR13;
    UINT64 RegR14;
    UINT64 RegR15;
    UINT64 RegRip;
    UINT64 RegEFlags;
    UINT64 RegDr0;
    UINT64 RegDr1;
    UINT64 RegDr2;
    UINT64 RegDr3;
    UINT64 RegDr6;
    UINT64 RegDr7;
    UINT64 StackSnapshotAddress;
    UINT32 StackSnapshotSize;
    UINT8 StackSnapshot[BLACKBIRD_MAX_STACK_SNAPSHOT_BYTES];
} BLACKBIRD_HANDLE_EVENT, *PBLACKBIRD_HANDLE_EVENT;

typedef struct _BLACKBIRD_THREAD_EVENT
{
    UINT64 ProcessId;
    UINT64 ThreadId;
    UINT64 CreatorPid;
    UINT64 StartAddress;
    UINT64 ImageBase;
    UINT64 ImageSize;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[BLACKBIRD_MAX_EVENT_FRAMES];
} BLACKBIRD_THREAD_EVENT, *PBLACKBIRD_THREAD_EVENT;

typedef struct _BLACKBIRD_FILE_EVENT
{
    UINT64 ProcessId;
    UINT64 ThreadId;
    UINT64 FileObject;
    UINT64 FileId;
    UINT64 ByteOffset;
    UINT64 Length;
    UINT64 Status;
    UINT64 Information;
    UINT32 Operation;
    UINT32 MajorCode;
    UINT32 MinorCode;
    UINT32 IrpFlags;
    UINT32 CreateOptions;
    UINT32 CreateDisposition;
    UINT32 DesiredAccess;
    UINT32 ShareAccess;
    UINT32 Flags;
    WCHAR Path[BLACKBIRD_MAX_FILE_PATH_CHARS];
} BLACKBIRD_FILE_EVENT, *PBLACKBIRD_FILE_EVENT;

typedef struct _BLACKBIRD_EVENT_RECORD
{
    BLACKBIRD_EVENT_HEADER Header;
    union
    {
        BLACKBIRD_HANDLE_EVENT Handle;
        BLACKBIRD_THREAD_EVENT Thread;
        BLACKBIRD_FILE_EVENT FileSystem;
    } Data;
} BLACKBIRD_EVENT_RECORD, *PBLACKBIRD_EVENT_RECORD;

typedef struct _BLACKBIRD_STATS_RESPONSE
{
    UINT32 SubscriptionCount;
    UINT32 QueueDepth;
    UINT32 DroppedEvents;
    UINT32 Reserved;
} BLACKBIRD_STATS_RESPONSE, *PBLACKBIRD_STATS_RESPONSE;

typedef struct _BLACKBIRD_HEALTH_RESPONSE
{
    UINT32 HealthMask;
    UINT32 TamperMask;
    UINT32 Reserved0;
    UINT32 Reserved1;
} BLACKBIRD_HEALTH_RESPONSE, *PBLACKBIRD_HEALTH_RESPONSE;

#define BLACKBIRD_HEALTH_CONTROL_READY 0x00000001u
#define BLACKBIRD_HEALTH_ETW_READY 0x00000002u
#define BLACKBIRD_HEALTH_HANDLE_MONITOR_READY 0x00000004u
#define BLACKBIRD_HEALTH_THREAD_MONITOR_READY 0x00000008u
#define BLACKBIRD_HEALTH_PROCESS_MONITOR_READY 0x00000010u
#define BLACKBIRD_HEALTH_IMAGE_MONITOR_READY 0x00000020u
#define BLACKBIRD_HEALTH_REGISTRY_MONITOR_READY 0x00000040u
#define BLACKBIRD_HEALTH_APC_MONITOR_READY 0x00000080u
#define BLACKBIRD_HEALTH_FILESYSTEM_MONITOR_READY 0x00000100u
#define BLACKBIRD_HEALTH_CORRELATION_READY 0x00000200u
#define BLACKBIRD_HEALTH_HOLLOWING_ENGINE_READY 0x00000400u

#define BLACKBIRD_HANDLE_FLAG_EXEC_PROTECT 0x00000001
#define BLACKBIRD_HANDLE_FLAG_FROM_NTDLL 0x00000002
#define BLACKBIRD_HANDLE_FLAG_FROM_EXE 0x00000004
#define BLACKBIRD_HANDLE_FLAG_MEMORY_RELATED 0x00000008
#define BLACKBIRD_HANDLE_FLAG_THREAD_OBJECT 0x00000010
#define BLACKBIRD_HANDLE_FLAG_DUPLICATE_OPERATION 0x00000020
#define BLACKBIRD_HANDLE_FLAG_DEEP_PATH_CANDIDATE 0x00000040
#define BLACKBIRD_HANDLE_FLAG_DEEP_PATH_CAPTURED 0x00000080
#define BLACKBIRD_HANDLE_FLAG_DEEP_PATH_CACHE_HIT 0x00000100
#define BLACKBIRD_HANDLE_FLAG_RETURN_ADDRESS_VALID 0x00000200
#define BLACKBIRD_HANDLE_FLAG_STACK_VALIDATED 0x00000400
#define BLACKBIRD_HANDLE_FLAG_STACK_SPOOF_SUSPECT 0x00000800
#define BLACKBIRD_HANDLE_FLAG_SYSCALL_EXPORT_MATCH 0x00001000
#define BLACKBIRD_HANDLE_FLAG_SYSCALL_EXPORT_MISMATCH 0x00002000
#define BLACKBIRD_HANDLE_FLAG_MODULE_CHAIN_SANE 0x00004000
#define BLACKBIRD_HANDLE_FLAG_UNWIND_METADATA_VALID 0x00008000
#define BLACKBIRD_HANDLE_FLAG_TEB_STACK_BOUNDS_VALID 0x00010000
#define BLACKBIRD_HANDLE_FLAG_FRAMES_OUTSIDE_TEB_STACK 0x00020000

#define BLACKBIRD_HANDLE_CAPTURE_CONTEXT_VALID 0x00000001
#define BLACKBIRD_HANDLE_CAPTURE_DEBUG_REGS_VALID 0x00000002
#define BLACKBIRD_HANDLE_CAPTURE_FULL_FRAMES_VALID 0x00000004
#define BLACKBIRD_HANDLE_CAPTURE_STACK_SNAPSHOT_VALID 0x00000008

#define BLACKBIRD_THREAD_FLAG_GOT_START 0x00000001
#define BLACKBIRD_THREAD_FLAG_GOT_RANGE 0x00000002
#define BLACKBIRD_THREAD_FLAG_REMOTE_CREATOR 0x00000004
#define BLACKBIRD_THREAD_FLAG_OUTSIDE_MAIN_IMG 0x00000008
#define BLACKBIRD_THREAD_FLAG_CORRELATED_INTENT 0x00000010
#define BLACKBIRD_THREAD_FLAG_CORR_MEMORY 0x00000020
#define BLACKBIRD_THREAD_FLAG_CORR_THREAD_CTX 0x00000040
#define BLACKBIRD_THREAD_FLAG_CORR_DUP_HANDLE 0x00000080
#define BLACKBIRD_THREAD_FLAG_START_REGION_EXEC 0x00000100

#define BLACKBIRD_FILE_FLAG_PRE_OPERATION 0x00000001
#define BLACKBIRD_FILE_FLAG_POST_OPERATION 0x00000002
#define BLACKBIRD_FILE_FLAG_PAGING_IO 0x00000004
#define BLACKBIRD_FILE_FLAG_SYNCHRONOUS_IO 0x00000008
#define BLACKBIRD_FILE_FLAG_NON_CACHED_IO 0x00000010
#define BLACKBIRD_FILE_FLAG_DIRECTORY_FILE 0x00000020
#define BLACKBIRD_FILE_FLAG_DELETE_ON_CLOSE 0x00000040
#define BLACKBIRD_FILE_FLAG_REPARSE_POINT 0x00000080
#define BLACKBIRD_FILE_FLAG_FAST_IO 0x00000100

#endif


