#ifndef SLEEPWALKER_IOCTL_H
#define SLEEPWALKER_IOCTL_H

#include <basetsd.h>

#ifndef CTL_CODE
#include <winioctl.h>
#endif

#define FILE_DEVICE_SLEEPWALKER 0x00008337

#define IOCTL_SLEEPWALKER_SUBSCRIBE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SLEEPWALKER_UNSUBSCRIBE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SLEEPWALKER_GET_EVENT CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x803, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_SLEEPWALKER_GET_STATS CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x804, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_SLEEPWALKER_SET_PIDS CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SLEEPWALKER_QUERY_PROCESS_IMAGE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x806, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_SLEEPWALKER_SET_SHUTDOWN_MODE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x807, METHOD_BUFFERED, FILE_WRITE_DATA)

#define SLEEPWALKER_STREAM_HANDLE 0x00000001
#define SLEEPWALKER_STREAM_MEMORY 0x00000002
#define SLEEPWALKER_STREAM_THREAD 0x00000004

#define SLEEPWALKER_MAX_EVENT_FRAMES 8
#define SLEEPWALKER_MAX_PID_LIST 64
#define SLEEPWALKER_MAX_IMAGE_PATH_CHARS 1024
#define SLEEPWALKER_MAX_DEEP_SAMPLE_BYTES 64

typedef enum _SLEEPWALKER_EVENT_TYPE
{
    SleepwalkerEventTypeNone = 0,
    SleepwalkerEventTypeHandle = 1,
    SleepwalkerEventTypeThread = 2
} SLEEPWALKER_EVENT_TYPE;

typedef enum _SLEEPWALKER_HANDLE_CLASS
{
    SleepwalkerHandleClassUnknown = 0,
    SleepwalkerHandleClassLegitimateSyscall = 1,
    SleepwalkerHandleClassDirectSyscallSuspect = 2
} SLEEPWALKER_HANDLE_CLASS;

typedef struct _SLEEPWALKER_SUBSCRIBE_REQUEST
{
    UINT32 ProcessId;
    UINT32 StreamMask;
} SLEEPWALKER_SUBSCRIBE_REQUEST, *PSLEEPWALKER_SUBSCRIBE_REQUEST;

typedef struct _SLEEPWALKER_UNSUBSCRIBE_REQUEST
{
    UINT32 ProcessId;
} SLEEPWALKER_UNSUBSCRIBE_REQUEST, *PSLEEPWALKER_UNSUBSCRIBE_REQUEST;

typedef struct _SLEEPWALKER_GET_EVENT_REQUEST
{
    UINT32 TimeoutMs;
} SLEEPWALKER_GET_EVENT_REQUEST, *PSLEEPWALKER_GET_EVENT_REQUEST;

typedef struct _SLEEPWALKER_SET_PIDS_REQUEST
{
    UINT32 StreamMask;
    UINT32 ProcessCount;
    UINT32 ProcessIds[SLEEPWALKER_MAX_PID_LIST];
} SLEEPWALKER_SET_PIDS_REQUEST, *PSLEEPWALKER_SET_PIDS_REQUEST;

typedef struct _SLEEPWALKER_QUERY_PROCESS_IMAGE_REQUEST
{
    UINT32 ProcessId;
} SLEEPWALKER_QUERY_PROCESS_IMAGE_REQUEST, *PSLEEPWALKER_QUERY_PROCESS_IMAGE_REQUEST;

typedef struct _SLEEPWALKER_QUERY_PROCESS_IMAGE_RESPONSE
{
    UINT32 ProcessId;
    INT32 Status;
    WCHAR ImagePath[SLEEPWALKER_MAX_IMAGE_PATH_CHARS];
} SLEEPWALKER_QUERY_PROCESS_IMAGE_RESPONSE, *PSLEEPWALKER_QUERY_PROCESS_IMAGE_RESPONSE;

typedef struct _SLEEPWALKER_EVENT_HEADER
{
    UINT32 Size;
    UINT32 Type;
    UINT32 StreamMask;
    UINT32 Sequence;
    INT64 TimestampQpc;
} SLEEPWALKER_EVENT_HEADER, *PSLEEPWALKER_EVENT_HEADER;

typedef struct _SLEEPWALKER_HANDLE_EVENT
{
    UINT64 CallerPid;
    UINT64 TargetPid;
    UINT32 DesiredAccess;
    UINT32 ClassId;
    UINT64 OriginAddress;
    UINT32 OriginProtect;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[SLEEPWALKER_MAX_EVENT_FRAMES];
    INT32 StatusOpenProcess;
    INT32 StatusBasicInfo;
    INT32 StatusSectionName;
    UINT64 DeepAllocationBase;
    UINT64 DeepRegionSize;
    UINT32 DeepRegionProtect;
    UINT32 DeepRegionState;
    UINT32 DeepRegionType;
    UINT32 DeepSampleSize;
    UINT8 DeepSample[SLEEPWALKER_MAX_DEEP_SAMPLE_BYTES];
    WCHAR OriginPath[260];
} SLEEPWALKER_HANDLE_EVENT, *PSLEEPWALKER_HANDLE_EVENT;

typedef struct _SLEEPWALKER_THREAD_EVENT
{
    UINT64 ProcessId;
    UINT64 ThreadId;
    UINT64 CreatorPid;
    UINT64 StartAddress;
    UINT64 ImageBase;
    UINT64 ImageSize;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[SLEEPWALKER_MAX_EVENT_FRAMES];
} SLEEPWALKER_THREAD_EVENT, *PSLEEPWALKER_THREAD_EVENT;

typedef struct _SLEEPWALKER_EVENT_RECORD
{
    SLEEPWALKER_EVENT_HEADER Header;
    union
    {
        SLEEPWALKER_HANDLE_EVENT Handle;
        SLEEPWALKER_THREAD_EVENT Thread;
    } Data;
} SLEEPWALKER_EVENT_RECORD, *PSLEEPWALKER_EVENT_RECORD;

typedef struct _SLEEPWALKER_STATS_RESPONSE
{
    UINT32 SubscriptionCount;
    UINT32 QueueDepth;
    UINT32 DroppedEvents;
    UINT32 Reserved;
} SLEEPWALKER_STATS_RESPONSE, *PSLEEPWALKER_STATS_RESPONSE;

#define SLEEPWALKER_HANDLE_FLAG_EXEC_PROTECT 0x00000001
#define SLEEPWALKER_HANDLE_FLAG_FROM_NTDLL 0x00000002
#define SLEEPWALKER_HANDLE_FLAG_FROM_EXE 0x00000004
#define SLEEPWALKER_HANDLE_FLAG_MEMORY_RELATED 0x00000008
#define SLEEPWALKER_HANDLE_FLAG_THREAD_OBJECT 0x00000010
#define SLEEPWALKER_HANDLE_FLAG_DUPLICATE_OPERATION 0x00000020
#define SLEEPWALKER_HANDLE_FLAG_DEEP_PATH_CANDIDATE 0x00000040
#define SLEEPWALKER_HANDLE_FLAG_DEEP_PATH_CAPTURED 0x00000080
#define SLEEPWALKER_HANDLE_FLAG_DEEP_PATH_CACHE_HIT 0x00000100

#define SLEEPWALKER_THREAD_FLAG_GOT_START 0x00000001
#define SLEEPWALKER_THREAD_FLAG_GOT_RANGE 0x00000002
#define SLEEPWALKER_THREAD_FLAG_REMOTE_CREATOR 0x00000004
#define SLEEPWALKER_THREAD_FLAG_OUTSIDE_MAIN_IMG 0x00000008
#define SLEEPWALKER_THREAD_FLAG_CORRELATED_INTENT 0x00000010
#define SLEEPWALKER_THREAD_FLAG_CORR_MEMORY 0x00000020
#define SLEEPWALKER_THREAD_FLAG_CORR_THREAD_CTX 0x00000040
#define SLEEPWALKER_THREAD_FLAG_CORR_DUP_HANDLE 0x00000080
#define SLEEPWALKER_THREAD_FLAG_START_REGION_EXEC 0x00000100

#endif
