#ifndef SLEEPWALKER_IOCTL_H
#define SLEEPWALKER_IOCTL_H

#include <basetsd.h>

#ifndef CTL_CODE
#include <winioctl.h>
#endif

#define FILE_DEVICE_SLEEPWALKER 0x00008337

#define IOCTL_SLEEPWALKER_SUBSCRIBE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SLEEPWALKER_UNSUBSCRIBE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SLEEPWALKER_GET_EVENT CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x803, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_SLEEPWALKER_GET_STATS CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x804, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_SLEEPWALKER_SET_PIDS CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SLEEPWALKER_QUERY_PROCESS_IMAGE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x806, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_SLEEPWALKER_SET_SHUTDOWN_MODE CTL_CODE(FILE_DEVICE_SLEEPWALKER, 0x807, METHOD_BUFFERED, FILE_WRITE_DATA)

#define SLEEPWALKER_STREAM_HANDLE 0x00000001
#define SLEEPWALKER_STREAM_MEMORY 0x00000002
#define SLEEPWALKER_STREAM_THREAD 0x00000004
#define SLEEPWALKER_STREAM_FILESYSTEM 0x00000008

#define SLEEPWALKER_MAX_EVENT_FRAMES 8
#define SLEEPWALKER_MAX_FULL_EVENT_FRAMES 32
#define SLEEPWALKER_MAX_PID_LIST 64
#define SLEEPWALKER_MAX_IMAGE_PATH_CHARS 1024
#define SLEEPWALKER_MAX_DEEP_SAMPLE_BYTES 64
#define SLEEPWALKER_MAX_STACK_SNAPSHOT_BYTES 256
#define SLEEPWALKER_MAX_FILE_PATH_CHARS 520

typedef enum _SLEEPWALKER_EVENT_TYPE
{
    SleepwalkerEventTypeNone = 0,
    SleepwalkerEventTypeHandle = 1,
    SleepwalkerEventTypeThread = 2,
    SleepwalkerEventTypeFileSystem = 3
} SLEEPWALKER_EVENT_TYPE;

typedef enum _SLEEPWALKER_FILE_OPERATION
{
    SleepwalkerFileOperationUnknown = 0,
    SleepwalkerFileOperationCreate = 1,
    SleepwalkerFileOperationRead = 2,
    SleepwalkerFileOperationWrite = 3,
    SleepwalkerFileOperationClose = 4,
    SleepwalkerFileOperationCleanup = 5,
    SleepwalkerFileOperationSetInformation = 6,
    SleepwalkerFileOperationQueryInformation = 7,
    SleepwalkerFileOperationDirectoryControl = 8,
    SleepwalkerFileOperationFsControl = 9
} SLEEPWALKER_FILE_OPERATION;

typedef enum _SLEEPWALKER_HANDLE_CLASS
{
    SleepwalkerHandleClassUnknown = 0,
    SleepwalkerHandleClassLegitimateSyscall = 1,
    SleepwalkerHandleClassDirectSyscallSuspect = 2
} SLEEPWALKER_HANDLE_CLASS;

typedef struct _SLEEPWALKER_SUBSCRIBE_REQUEST
{
    UINT32 ProcessId;
    UINT32 StreamMask;
} SLEEPWALKER_SUBSCRIBE_REQUEST, *PSLEEPWALKER_SUBSCRIBE_REQUEST;

typedef struct _SLEEPWALKER_UNSUBSCRIBE_REQUEST
{
    UINT32 ProcessId;
} SLEEPWALKER_UNSUBSCRIBE_REQUEST, *PSLEEPWALKER_UNSUBSCRIBE_REQUEST;

typedef struct _SLEEPWALKER_GET_EVENT_REQUEST
{
    UINT32 TimeoutMs;
} SLEEPWALKER_GET_EVENT_REQUEST, *PSLEEPWALKER_GET_EVENT_REQUEST;

typedef struct _SLEEPWALKER_SET_PIDS_REQUEST
{
    UINT32 StreamMask;
    UINT32 ProcessCount;
    UINT32 ProcessIds[SLEEPWALKER_MAX_PID_LIST];
} SLEEPWALKER_SET_PIDS_REQUEST, *PSLEEPWALKER_SET_PIDS_REQUEST;

typedef struct _SLEEPWALKER_QUERY_PROCESS_IMAGE_REQUEST
{
    UINT32 ProcessId;
} SLEEPWALKER_QUERY_PROCESS_IMAGE_REQUEST, *PSLEEPWALKER_QUERY_PROCESS_IMAGE_REQUEST;

typedef struct _SLEEPWALKER_QUERY_PROCESS_IMAGE_RESPONSE
{
    UINT32 ProcessId;
    INT32 Status;
    WCHAR ImagePath[SLEEPWALKER_MAX_IMAGE_PATH_CHARS];
} SLEEPWALKER_QUERY_PROCESS_IMAGE_RESPONSE, *PSLEEPWALKER_QUERY_PROCESS_IMAGE_RESPONSE;

typedef struct _SLEEPWALKER_EVENT_HEADER
{
    UINT32 Size;
    UINT32 Type;
    UINT32 StreamMask;
    UINT32 Sequence;
    INT64 TimestampQpc;
} SLEEPWALKER_EVENT_HEADER, *PSLEEPWALKER_EVENT_HEADER;

typedef struct _SLEEPWALKER_HANDLE_EVENT
{
    UINT64 CallerPid;
    UINT64 TargetPid;
    UINT32 DesiredAccess;
    UINT32 ClassId;
    UINT64 OriginAddress;
    UINT32 OriginProtect;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[SLEEPWALKER_MAX_EVENT_FRAMES];
    INT32 StatusOpenProcess;
    INT32 StatusBasicInfo;
    INT32 StatusSectionName;
    UINT64 DeepAllocationBase;
    UINT64 DeepRegionSize;
    UINT32 DeepRegionProtect;
    UINT32 DeepRegionState;
    UINT32 DeepRegionType;
    UINT32 DeepSampleSize;
    UINT8 DeepSample[SLEEPWALKER_MAX_DEEP_SAMPLE_BYTES];
    WCHAR OriginPath[260];
    UINT32 CaptureFlags;
    UINT32 FullFrameCount;
    UINT64 FullFrames[SLEEPWALKER_MAX_FULL_EVENT_FRAMES];
    UINT64 RegRax;
    UINT64 RegRbx;
    UINT64 RegRcx;
    UINT64 RegRdx;
    UINT64 RegRsi;
    UINT64 RegRdi;
    UINT64 RegRbp;
    UINT64 RegRsp;
    UINT64 RegR8;
    UINT64 RegR9;
    UINT64 RegR10;
    UINT64 RegR11;
    UINT64 RegR12;
    UINT64 RegR13;
    UINT64 RegR14;
    UINT64 RegR15;
    UINT64 RegRip;
    UINT64 RegEFlags;
    UINT64 RegDr0;
    UINT64 RegDr1;
    UINT64 RegDr2;
    UINT64 RegDr3;
    UINT64 RegDr6;
    UINT64 RegDr7;
    UINT64 StackSnapshotAddress;
    UINT32 StackSnapshotSize;
    UINT8 StackSnapshot[SLEEPWALKER_MAX_STACK_SNAPSHOT_BYTES];
} SLEEPWALKER_HANDLE_EVENT, *PSLEEPWALKER_HANDLE_EVENT;

typedef struct _SLEEPWALKER_THREAD_EVENT
{
    UINT64 ProcessId;
    UINT64 ThreadId;
    UINT64 CreatorPid;
    UINT64 StartAddress;
    UINT64 ImageBase;
    UINT64 ImageSize;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[SLEEPWALKER_MAX_EVENT_FRAMES];
} SLEEPWALKER_THREAD_EVENT, *PSLEEPWALKER_THREAD_EVENT;

typedef struct _SLEEPWALKER_FILE_EVENT
{
    UINT64 ProcessId;
    UINT64 ThreadId;
    UINT64 FileObject;
    UINT64 FileId;
    UINT64 ByteOffset;
    UINT64 Length;
    UINT64 Status;
    UINT64 Information;
    UINT32 Operation;
    UINT32 MajorCode;
    UINT32 MinorCode;
    UINT32 IrpFlags;
    UINT32 CreateOptions;
    UINT32 CreateDisposition;
    UINT32 DesiredAccess;
    UINT32 ShareAccess;
    UINT32 Flags;
    WCHAR Path[SLEEPWALKER_MAX_FILE_PATH_CHARS];
} SLEEPWALKER_FILE_EVENT, *PSLEEPWALKER_FILE_EVENT;

typedef struct _SLEEPWALKER_EVENT_RECORD
{
    SLEEPWALKER_EVENT_HEADER Header;
    union
    {
        SLEEPWALKER_HANDLE_EVENT Handle;
        SLEEPWALKER_THREAD_EVENT Thread;
        SLEEPWALKER_FILE_EVENT FileSystem;
    } Data;
} SLEEPWALKER_EVENT_RECORD, *PSLEEPWALKER_EVENT_RECORD;

typedef struct _SLEEPWALKER_STATS_RESPONSE
{
    UINT32 SubscriptionCount;
    UINT32 QueueDepth;
    UINT32 DroppedEvents;
    UINT32 Reserved;
} SLEEPWALKER_STATS_RESPONSE, *PSLEEPWALKER_STATS_RESPONSE;

#define SLEEPWALKER_HANDLE_FLAG_EXEC_PROTECT 0x00000001
#define SLEEPWALKER_HANDLE_FLAG_FROM_NTDLL 0x00000002
#define SLEEPWALKER_HANDLE_FLAG_FROM_EXE 0x00000004
#define SLEEPWALKER_HANDLE_FLAG_MEMORY_RELATED 0x00000008
#define SLEEPWALKER_HANDLE_FLAG_THREAD_OBJECT 0x00000010
#define SLEEPWALKER_HANDLE_FLAG_DUPLICATE_OPERATION 0x00000020
#define SLEEPWALKER_HANDLE_FLAG_DEEP_PATH_CANDIDATE 0x00000040
#define SLEEPWALKER_HANDLE_FLAG_DEEP_PATH_CAPTURED 0x00000080
#define SLEEPWALKER_HANDLE_FLAG_DEEP_PATH_CACHE_HIT 0x00000100
#define SLEEPWALKER_HANDLE_FLAG_RETURN_ADDRESS_VALID 0x00000200
#define SLEEPWALKER_HANDLE_FLAG_STACK_VALIDATED 0x00000400
#define SLEEPWALKER_HANDLE_FLAG_STACK_SPOOF_SUSPECT 0x00000800
#define SLEEPWALKER_HANDLE_FLAG_SYSCALL_EXPORT_MATCH 0x00001000
#define SLEEPWALKER_HANDLE_FLAG_SYSCALL_EXPORT_MISMATCH 0x00002000
#define SLEEPWALKER_HANDLE_FLAG_MODULE_CHAIN_SANE 0x00004000
#define SLEEPWALKER_HANDLE_FLAG_UNWIND_METADATA_VALID 0x00008000
#define SLEEPWALKER_HANDLE_FLAG_TEB_STACK_BOUNDS_VALID 0x00010000
#define SLEEPWALKER_HANDLE_FLAG_FRAMES_OUTSIDE_TEB_STACK 0x00020000

#define SLEEPWALKER_HANDLE_CAPTURE_CONTEXT_VALID 0x00000001
#define SLEEPWALKER_HANDLE_CAPTURE_DEBUG_REGS_VALID 0x00000002
#define SLEEPWALKER_HANDLE_CAPTURE_FULL_FRAMES_VALID 0x00000004
#define SLEEPWALKER_HANDLE_CAPTURE_STACK_SNAPSHOT_VALID 0x00000008

#define SLEEPWALKER_THREAD_FLAG_GOT_START 0x00000001
#define SLEEPWALKER_THREAD_FLAG_GOT_RANGE 0x00000002
#define SLEEPWALKER_THREAD_FLAG_REMOTE_CREATOR 0x00000004
#define SLEEPWALKER_THREAD_FLAG_OUTSIDE_MAIN_IMG 0x00000008
#define SLEEPWALKER_THREAD_FLAG_CORRELATED_INTENT 0x00000010
#define SLEEPWALKER_THREAD_FLAG_CORR_MEMORY 0x00000020
#define SLEEPWALKER_THREAD_FLAG_CORR_THREAD_CTX 0x00000040
#define SLEEPWALKER_THREAD_FLAG_CORR_DUP_HANDLE 0x00000080
#define SLEEPWALKER_THREAD_FLAG_START_REGION_EXEC 0x00000100

#define SLEEPWALKER_FILE_FLAG_PRE_OPERATION 0x00000001
#define SLEEPWALKER_FILE_FLAG_POST_OPERATION 0x00000002
#define SLEEPWALKER_FILE_FLAG_PAGING_IO 0x00000004
#define SLEEPWALKER_FILE_FLAG_SYNCHRONOUS_IO 0x00000008
#define SLEEPWALKER_FILE_FLAG_NON_CACHED_IO 0x00000010
#define SLEEPWALKER_FILE_FLAG_DIRECTORY_FILE 0x00000020
#define SLEEPWALKER_FILE_FLAG_DELETE_ON_CLOSE 0x00000040
#define SLEEPWALKER_FILE_FLAG_REPARSE_POINT 0x00000080
#define SLEEPWALKER_FILE_FLAG_FAST_IO 0x00000100

#endif
