#ifndef STINGER_IOCTL_H
#define STINGER_IOCTL_H

#include <basetsd.h>

#ifndef CTL_CODE
#include <winioctl.h>
#endif

#define FILE_DEVICE_STINGER 0x00008337

#define IOCTL_STINGER_SUBSCRIBE   CTL_CODE(FILE_DEVICE_STINGER, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_STINGER_UNSUBSCRIBE CTL_CODE(FILE_DEVICE_STINGER, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_STINGER_GET_EVENT   CTL_CODE(FILE_DEVICE_STINGER, 0x803, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_STINGER_GET_STATS   CTL_CODE(FILE_DEVICE_STINGER, 0x804, METHOD_BUFFERED, FILE_READ_DATA)

#define STINGER_STREAM_HANDLE 0x00000001
#define STINGER_STREAM_MEMORY 0x00000002
#define STINGER_STREAM_THREAD 0x00000004

#define STINGER_MAX_EVENT_FRAMES 8

typedef enum _STINGER_EVENT_TYPE {
    StingerEventTypeNone = 0,
    StingerEventTypeHandle = 1,
    StingerEventTypeThread = 2
} STINGER_EVENT_TYPE;

typedef enum _STINGER_HANDLE_CLASS {
    StingerHandleClassUnknown = 0,
    StingerHandleClassLegitimateSyscall = 1,
    StingerHandleClassDirectSyscallSuspect = 2
} STINGER_HANDLE_CLASS;

typedef struct _STINGER_SUBSCRIBE_REQUEST {
    UINT32 ProcessId;
    UINT32 StreamMask;
} STINGER_SUBSCRIBE_REQUEST, *PSTINGER_SUBSCRIBE_REQUEST;

typedef struct _STINGER_UNSUBSCRIBE_REQUEST {
    UINT32 ProcessId;
} STINGER_UNSUBSCRIBE_REQUEST, *PSTINGER_UNSUBSCRIBE_REQUEST;

typedef struct _STINGER_GET_EVENT_REQUEST {
    UINT32 TimeoutMs;
} STINGER_GET_EVENT_REQUEST, *PSTINGER_GET_EVENT_REQUEST;

typedef struct _STINGER_EVENT_HEADER {
    UINT32 Size;
    UINT32 Type;
    UINT32 StreamMask;
    UINT32 Sequence;
    INT64 TimestampQpc;
} STINGER_EVENT_HEADER, *PSTINGER_EVENT_HEADER;

typedef struct _STINGER_HANDLE_EVENT {
    UINT64 CallerPid;
    UINT64 TargetPid;
    UINT32 DesiredAccess;
    UINT32 ClassId;
    UINT64 OriginAddress;
    UINT32 OriginProtect;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[STINGER_MAX_EVENT_FRAMES];
    INT32 StatusOpenProcess;
    INT32 StatusBasicInfo;
    INT32 StatusSectionName;
    WCHAR OriginPath[260];
} STINGER_HANDLE_EVENT, *PSTINGER_HANDLE_EVENT;

typedef struct _STINGER_THREAD_EVENT {
    UINT64 ProcessId;
    UINT64 ThreadId;
    UINT64 CreatorPid;
    UINT64 StartAddress;
    UINT64 ImageBase;
    UINT64 ImageSize;
    UINT32 Flags;
    UINT32 FrameCount;
    UINT64 Frames[STINGER_MAX_EVENT_FRAMES];
} STINGER_THREAD_EVENT, *PSTINGER_THREAD_EVENT;

typedef struct _STINGER_EVENT_RECORD {
    STINGER_EVENT_HEADER Header;
    union {
        STINGER_HANDLE_EVENT Handle;
        STINGER_THREAD_EVENT Thread;
    } Data;
} STINGER_EVENT_RECORD, *PSTINGER_EVENT_RECORD;

typedef struct _STINGER_STATS_RESPONSE {
    UINT32 SubscriptionCount;
    UINT32 QueueDepth;
    UINT32 DroppedEvents;
    UINT32 Reserved;
} STINGER_STATS_RESPONSE, *PSTINGER_STATS_RESPONSE;

#define STINGER_HANDLE_FLAG_EXEC_PROTECT      0x00000001
#define STINGER_HANDLE_FLAG_FROM_NTDLL        0x00000002
#define STINGER_HANDLE_FLAG_FROM_EXE          0x00000004
#define STINGER_HANDLE_FLAG_MEMORY_RELATED    0x00000008

#define STINGER_THREAD_FLAG_GOT_START         0x00000001
#define STINGER_THREAD_FLAG_GOT_RANGE         0x00000002
#define STINGER_THREAD_FLAG_REMOTE_CREATOR    0x00000004
#define STINGER_THREAD_FLAG_OUTSIDE_MAIN_IMG  0x00000008

#endif
